title: Low-Fantasy D20
description: A tactical TTRPG with gritty combat made for people looking for something different than your usual D&D.
theme: just-the-docs

url: https://filipesoaresbranco-lab.github.io/low-fantasyd20

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
