title: Low-Fantasy D20
description: A tactical TTRPG with gritty combat made for people looking for something different than your usual D&D.
theme: just-the-docs

color_scheme: dark

url: https://filipesoaresbranco-lab.github.io/low-fantasyd20

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
